apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chaos-app
  template:
    metadata:
      labels:
        app: chaos-app
    spec:
      serviceAccountName: github-actions
    spec:
      containers:
      - name: chaos-app
        image: nginx
        ports:
        - containerPort: 80
