# k8s/chaos-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-app
  namespace: chaos-testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaos-app
  template:
    metadata:
      labels:
        app: chaos-app
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-app
  namespace: chaos-testing
spec:
  selector:
    app: chaos-app
  ports:
    - port: 80
      targetPort: 80
