apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-chaos-app
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - chaos-testing
    labelSelectors:
      app: chaos-app
  duration: "30s"
  scheduler:
    cron: "@every 1m"
