apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-app
  namespace: chaos-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chaos-app
  template:
    metadata:
      labels:
        app: chaos-app
    spec:
      serviceAccountName: github-actions   # 🧠 This must exist
      containers:
        - name: chaos-app
          image: nginx
          ports:
            - containerPort: 80
